/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2016-05-10 02:09:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registrosocio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cooperativa San Lorenzo</title>\r\n");
      out.write("<!-- \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\r\n");
      out.write(" -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.3.min.js\" integrity=\"sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tocultarDatosAfiliacion();\r\n");
      out.write("\tconsole.log($(\"#tpoTrabajador\").val());\r\n");
      out.write("\t$('#btnBuscar').click(function(e) {\r\n");
      out.write("\t\tvar dni = $('#txtbuscarPersona').val();\r\n");
      out.write("\t\tif(dni.length > 0) {\r\n");
      out.write("\t\t\t$(\"#mensaje\").html(\"\");\r\n");
      out.write("\t\t\t// Si en vez de por post lo queremos hacer por get, cambiamos el $.post por $.get\r\n");
      out.write("\t\t\t$.post('buscarsocio.html', {\r\n");
      out.write("\t\t\t\tDNI : dni\r\n");
      out.write("\t\t\t}, function(respuesta) {\r\n");
      out.write("\t\t\t\t$('#tabla').html(respuesta).show();\r\n");
      out.write("\t\t\t\tmostrarDatosAfiliacion();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\t$('#tabla').html(\"\").hide();\r\n");
      out.write("\t\t\t$(\"#mensaje\").html(\"Ingresar un dni válido\");\r\n");
      out.write("\t\t\tocultarDatosAfiliacion();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#btnRegistrarSocio').click(function(e){\r\n");
      out.write("\t\tvar id = $(\"#codigoPersonaN\").text();\r\n");
      out.write("\t\tvar nombres = $(\"#nombres\").text();\r\n");
      out.write("\t\tvar apellidoP = $(\"#apellidoP\").text();\r\n");
      out.write("\t\tvar apellidoM = $(\"#apellidoM\").text();\r\n");
      out.write("\t\tvar tpoPersona = $(\"#tpoPersona\").val();\r\n");
      out.write("\t\tvar aporteInicial = $(\"#txtAporteInicial\").val();\r\n");
      out.write("\t\tvar derInscripcion = $(\"#txtDerechoInscripcion\").val();\r\n");
      out.write("\t\tvar fondoMortuorio = $(\"#txtFondoMortuorio\").val();\r\n");
      out.write("\t\tvar tpoTrabajador = $(\"#tpoTrabajador\").val(); \r\n");
      out.write("\t\t$.post(\"registrarsocio.html\",{\r\n");
      out.write("\t\t\tID : id,\r\n");
      out.write("\t\t\tNombres : nombres,\r\n");
      out.write("\t\t\tApellidoP : apellidoP,\r\n");
      out.write("\t\t\tApellidoM : apellidoM,\r\n");
      out.write("\t\t\tAporteIni : aporteInicial,\r\n");
      out.write("\t\t\tDerInscri : derInscripcion,\r\n");
      out.write("\t\t\tFondoM : derInscripcion,\r\n");
      out.write("\t\t\tTpoTrab : tpoTrabajador,\r\n");
      out.write("\t\t\tTpoPer : tpoPersona\r\n");
      out.write("\t\t}, function(respuesta){\r\n");
      out.write("\t\t\t$(\"#resultado\").html(respuesta+\". Correcto\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function ocultarDatosAfiliacion(){\r\n");
      out.write("\t$(\"#datosAfiliacion\").hide();\r\n");
      out.write("}\r\n");
      out.write("function mostrarDatosAfiliacion(){\r\n");
      out.write("\t$(\"#datosAfiliacion\").show();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div><h2>Afiliación de Socio</h2>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label>Buscar Persona: </label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"txtbuscarPersona\" id=\"txtbuscarPersona\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"Buscar\" name=\"btnBuscar\" id=\"btnBuscar\"/>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"mensaje\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tabla\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"datosAfiliacion\">\r\n");
      out.write("\t\t<h2>Datos de Afiliación</h2>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<div id=\"resultado\"></div>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Aporte Inicial:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"txtAporteInicial\" id=\"txtAporteInicial\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Pago Derecho Inscripcion:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"txtDerechoInscripcion\" id=\"txtDerechoInscripcion\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Fondo Mortuorio:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"txtFondoMortuorio\" id=\"txtFondoMortuorio\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Tipo Trabajador:</td>\r\n");
      out.write("\t\t\t\t<td><select id=\"tpoTrabajador\" class=\"form-control\" name=\"cboTipoTrabajador\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t \t     <option value=\"0702\"> Dependiente </option>\r\n");
      out.write("\t\t\t\t \t     <option value=\"0703\"> Independiente </option>\r\n");
      out.write("\t\t\t\t \t     <option value=\"0704\"> Microempresario </option>\r\n");
      out.write("\t \t  \t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"center\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"Registrar Socio\" name=\"btnRegSocio\" id=\"btnRegistrarSocio\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
